# -*- coding: utf-8 -*-
"""Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cV3o8uqnWkS-3nmkaxUkPYqVtPBm-WDt
"""

!pip install openpyxl nltk wordcloud seaborn scikit-learn joblib streamlit

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk
import warnings
warnings.filterwarnings('ignore')
from wordcloud import WordCloud
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix)
import pickle

from google.colab import files
uploaded = files.upload()

df = pd.read_excel('/content/dataset.xlsx')
df

df.head(10)

df.tail()

df.columns

df.shape

df.size

df.isnull().sum()

df.info()

df.describe()

df.duplicated().sum()

df['title'] = df['title'].fillna('')
df['body'] = df['body'].fillna('')
df['rating'] = df['rating'].fillna(0)

print(df['rating'].value_counts().sort_index())

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='rating')
plt.title('Rating Distribution')
plt.xlabel('Rating')
plt.ylabel('Number of Reviews')
plt.show()

def rating_to_sentiment(rating):
    if rating <= 2:
        return 'negative'
    elif rating == 3:
        return 'neutral'
    else:
        return 'positive'

df['sentiment'] = df['rating'].apply(rating_to_sentiment)

print(df['sentiment'].value_counts())

plt.figure(figsize=(8,5))
sns.countplot(
    data=df,
    x='sentiment',
    order=['negative', 'neutral', 'positive'])
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.show()

pd.crosstab(df['rating'],df['sentiment'])

plt.figure(figsize=(8,5))
sns.countplot(
    data=df,
    x='rating',
    hue='sentiment'
)
plt.title('Rating vs Sentiment')
plt.xlabel('Rating')
plt.ylabel('Number of Reviews')
plt.show()

df['Review'] = (
    df['title'].astype(str)
    + ' '
    + df['body'].astype(str)
)

df[['title', 'body', 'Review', 'rating', 'sentiment']].head(10)

def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(
        r'http\S+|www\S+',
        ' ',
        text
    )
    text = re.sub(
        r'[^\w\s\u0900-\u097F]',
        ' ',
        text
    )
    text = re.sub(
        r'\s+',
        ' ',
        text
    ).strip()
    return text

df['Clean_Review'] = df['Review'].apply(clean_text)

df[['Review', 'Clean_Review']].head(10)

df[df['Clean_Review'].str.contains(
    r'[\u0900-\u097F]',
    regex=True,
    na=False
)][['Review', 'Clean_Review']].head(10)

df['Word_Count'] = df['Clean_Review'].apply(
    lambda x: len(x.split())
)

df[['Clean_Review', 'Word_Count']].head()

plt.figure(figsize=(10,5))
sns.histplot(
    df['Word_Count'],
    bins=30,
    kde=True)
plt.title('Review Word Count Distribution')
plt.xlabel('Number of Words')
plt.ylabel('Number of Reviews')
plt.show()

positive_text = ' '.join(
    df[
        df['sentiment'] == 'positive'
    ]['Clean_Review']
)
wordcloud_positive = WordCloud(
    width=1200,
    height=600,
    background_color='white'
).generate(positive_text)
plt.figure(figsize=(15,7))
plt.imshow(
    wordcloud_positive,
    interpolation='bilinear'
)
plt.axis('off')
plt.title('Positive Reviews WordCloud')
plt.show()

negative_text = ' '.join(
    df[
        df['sentiment'] == 'negative'
    ]['Clean_Review']
)
wordcloud_negative = WordCloud(
    width=1200,
    height=600,
    background_color='white'
).generate(negative_text)

plt.figure(figsize=(15,7))
plt.imshow(
    wordcloud_negative,
    interpolation='bilinear'
)
plt.axis('off')
plt.title('Negative Reviews WordCloud')
plt.show()

X = df['Clean_Review']
y = df['sentiment']

print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print(
    "Training TF-IDF shape:",
    X_train_tfidf.shape
)
print(
    "Testing TF-IDF shape:",
    X_test_tfidf.shape
)

features = tfidf.get_feature_names_out()
print("Number of features:", len(features))
print(features[:50])

lr_model = LogisticRegression(
    max_iter=2000,
    class_weight='balanced'
)
lr_model.fit(
    X_train_tfidf,
    y_train
)

y_pred_lr = lr_model.predict(
    X_test_tfidf
)

lr_accuracy = accuracy_score(
    y_test,
    y_pred_lr
)
print(
    "Logistic Regression Accuracy:",
    lr_accuracy
)

print(
    classification_report(
        y_test,
        y_pred_lr
    )
)

nb_model = MultinomialNB()
nb_model.fit(
    X_train_tfidf,
    y_train
)

y_pred_nb = nb_model.predict(
    X_test_tfidf
)

nb_accuracy = accuracy_score(
    y_test,
    y_pred_nb
)
print(
    "Naive Bayes Accuracy:",
    nb_accuracy
)

print(
    classification_report(
        y_test,
        y_pred_nb
    )
)

svm_model = LinearSVC(
    class_weight='balanced'
)
svm_model.fit(
    X_train_tfidf,
    y_train
)

y_pred_svm = svm_model.predict(
    X_test_tfidf
)

svm_accuracy = accuracy_score(
    y_test,
    y_pred_svm
)
print(
    "Linear SVM Accuracy:",
    svm_accuracy
)

print(
    classification_report(
        y_test,
        y_pred_svm
    )
)

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)
rf_model.fit(
    X_train_tfidf,
    y_train
)

y_pred_rf = rf_model.predict(
    X_test_tfidf
)

rf_accuracy = accuracy_score(
    y_test,
    y_pred_rf
)
print(
    "Random Forest Accuracy:",
    rf_accuracy
)

print(
    classification_report(
        y_test,
        y_pred_rf
    )
)

from sklearn.metrics import f1_score
rf_f1 = f1_score(y_test, y_pred_rf, average='weighted')
results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Naive Bayes',
        'Linear SVM',
        'Random Forest'
    ],

    'Accuracy': [
        lr_accuracy,
        nb_accuracy,
        svm_accuracy,
        rf_accuracy
    ],

    'F1 Score': [
        f1_score(y_test, y_pred_lr, average='weighted'),
        f1_score(y_test, y_pred_nb, average='weighted'),
        f1_score(y_test, y_pred_svm, average='weighted'),
        rf_f1
    ]
})

results.sort_values(
    'F1 Score',
    ascending=False
)

plt.figure(figsize=(10,5))
sns.barplot(
    data=results,
    x='Model',
    y='Accuracy'
)
plt.title('Model Accuracy Comparison')
plt.ylim(0,1)
plt.xticks(rotation=15)
plt.show()

best_model_name = results.loc[
    results['F1 Score'].idxmax(),
    'Model'
]
print("Best Model:", best_model_name)

if best_model_name == 'Logistic Regression':
    best_model = lr_model
    best_predictions = y_pred_lr
elif best_model_name == 'Naive Bayes':
    best_model = nb_model
    best_predictions = y_pred_nb
else:
    best_model = svm_model
    best_predictions = y_pred_svm

best_accuracy = accuracy_score(
    y_test,
    best_predictions
)
print(
    "Best Model:",
    best_model_name
)
print(
    "Best Accuracy:",
    best_accuracy
)

print(
    classification_report(
        y_test,
        best_predictions
    )
)

labels = [
    'negative',
    'neutral',
    'positive'
]
cm = confusion_matrix(
    y_test,
    best_predictions,
    labels=labels
)
print(cm)

plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=labels,
    yticklabels=labels
)
plt.title(
    'Confusion Matrix - ' + best_model_name
)
plt.xlabel('Predicted Sentiment')
plt.ylabel('Actual Sentiment')
plt.show()

!pip install joblib

import joblib

# Save trained ML model
joblib.dump(best_model, "model.pkl")

# Save trained TF-IDF vectorizer
joblib.dump(tfidf, "tfidf.pkl")

print("Model and TF-IDF vectorizer saved successfully!")

from google.colab import files

files.download("model.pkl")
files.download("tfidf.pkl")

